"""
Module for opening and processing raw recording data from .h5 files.

This module contains a function to open and process raw recording data, particularly from
files generated by Multi Channel Systems (MCS). It also supports simple HDF5 files with
a 'recording' dataset and 'sample_rate' attribute (e.g., exported by SpikeInterface).

Functions:
    file_opener_raw_recording_data(data_preprocessing_config): Opens a .h5 file
    and extracts recording data, electrode stream, and sampling frequency.
"""
import h5py
import numpy as np

# MCS PyData tools - optional, only needed for MCS files
try:
    import McsPy
    import McsPy.McsData
    from McsPy import ureg, Q_
    HAS_MCSPY = True
except ImportError:
    HAS_MCSPY = False


class SimpleChannelInfo:
    """Mock channel info class for simple HDF5 files."""
    def __init__(self, channel_id, label):
        self.channel_id = channel_id
        self.row_index = channel_id
        self.info = {'Label': label}


class SimpleElectrodeStream:
    """Mock electrode stream class for simple HDF5 files."""
    def __init__(self, num_channels):
        self.channel_infos = {}
        for i in range(num_channels):
            # Create labels like "Ch00", "Ch01", etc.
            label = f"Ch{i:02d}"
            self.channel_infos[i] = SimpleChannelInfo(i, label)


def get_channel_data(data_stream, channel_ids=[]):
    """
    Extracts signals from each channel_ids electrodes from MCS .h5 raw recording file

    Args:
        data_stream: data stream containing raw recording
        channel_ids: ids of electrodes to be extracted. If channel_ids = [], extract all

    Returns:
        signal_corrected: AD corrected signal (raw)

    Note:
        - Designed to extract data from .h5 files generated by Multi Channel Systems.
    """
    if channel_ids == []:
        signal = data_stream.channel_data[:, :]
    else:
        index_lst = list()
        for i in channel_ids:
            index_lst.append(data_stream.channel_infos[i].row_index)
        signal = data_stream.channel_data[index_lst, :]
    scale = data_stream.channel_infos[0].adc_step.magnitude
    signal_corrected = (signal - data_stream.channel_infos[0].get_field('ADZero')) * scale
    return signal_corrected


def _open_simple_hdf5(path, big_file=False):
    """
    Opens a simple HDF5 file with 'recording' dataset.

    Args:
        path: Path to the HDF5 file
        big_file: Whether to use chunked reading (not implemented for simple files)

    Returns:
        tuple: (recording_data, electrode_stream, fsample)
    """
    with h5py.File(path, 'r') as f:
        # Check for expected structure
        if 'recording' not in f:
            raise ValueError(f"HDF5 file {path} does not have a 'recording' dataset")

        # Get sample rate from attributes
        if 'sample_rate' in f.attrs:
            fsample = int(f.attrs['sample_rate'])
        elif 'sampling_frequency' in f.attrs:
            fsample = int(f.attrs['sampling_frequency'])
        else:
            raise ValueError(f"HDF5 file {path} does not have 'sample_rate' attribute")

        # Read the recording data
        # Shape is expected to be (num_frames, num_channels) based on export
        recording_data = f['recording'][:]

        # Data should already be in µV if exported by run_spike_sorting.py
        # If not, check for a scale attribute
        if 'scale_to_uV' in f.attrs:
            recording_data = recording_data * f.attrs['scale_to_uV']

        num_channels = recording_data.shape[1]

    # Create mock electrode stream
    electrode_stream = SimpleElectrodeStream(num_channels)

    return recording_data, electrode_stream, fsample


def _open_mcs_hdf5(path, big_file=False):
    """
    Opens an MCS HDF5 file using McsPy.

    Args:
        path: Path to the HDF5 file
        big_file: Whether to use chunked reading for large files

    Returns:
        tuple: (recording_data, electrode_stream, fsample)
    """
    if not HAS_MCSPY:
        raise ImportError("McsPy is required to open MCS HDF5 files. Install with: pip install McsPyDataTools")

    file = McsPy.McsData.RawData(path)
    electrode_stream = file.recordings[0].analog_streams[0]
    fsample = int(electrode_stream.channel_infos[0].sampling_frequency.magnitude)

    if big_file:
        step_size = 10
        min_step = 0
        max_step = 60
        for i in range(min_step, max_step, step_size):
            scale_factor_for_uV = Q_(1, 'volt').to(ureg.uV).magnitude
            if i == min_step:
                recording_data = (get_channel_data(electrode_stream, channel_ids=[j for j in range(i, i + step_size)]) * scale_factor_for_uV).T
            else:
                recording_data = np.concatenate((recording_data, (get_channel_data(electrode_stream, channel_ids=[j for j in range(i, i + step_size)]) * scale_factor_for_uV).T), axis=1)
            print("iteration", i + step_size, "completed")
    else:
        signal = get_channel_data(electrode_stream, channel_ids=[])
        scale_factor_for_uV = Q_(1, 'volt').to(ureg.uV).magnitude
        recording_data = signal * scale_factor_for_uV.T

    return recording_data, electrode_stream, fsample


def file_opener_raw_recording_data(data_preprocessing_config):
    """
    Opens a .h5 file and extracts raw recording data, electrode stream, and sampling frequency.

    This function opens a .h5 file and extracts the raw recording data, the electrode stream,
    and the sampling frequency. It supports both MCS HDF5 files and simple HDF5 files with
    a 'recording' dataset.

    Args:
        data_preprocessing_config: Configuration for data preprocessing

    Returns:
        tuple: A tuple containing:
            - recording_data (numpy.ndarray): Array containing the raw recording data.
                                             Shape = (recorded data points, number of electrodes)
            - electrode_stream: The electrode stream object (MCS or mock SimpleElectrodeStream).
            - fsample (int): Sampling frequency in Hz.

    Note:
        - Supports both MCS HDF5 files (via McsPy) and simple HDF5 files.
        - For MCS files, requires McsPyDataTools package.
        - For simple HDF5 files, expects 'recording' dataset and 'sample_rate' attribute.
    """
    path = data_preprocessing_config.DATA_PATH
    big_file = data_preprocessing_config.BIG_FILE

    # First, check if this is an MCS file or a simple HDF5 file
    try:
        with h5py.File(path, 'r') as f:
            is_mcs_file = 'McsHdf5ProtocolType' in f.attrs
            is_simple_file = 'recording' in f
    except Exception as e:
        raise IOError(f"Could not open HDF5 file: {path}. Error: {e}")

    if is_mcs_file:
        print(f"[file_opener] Detected MCS HDF5 file: {path}")
        return _open_mcs_hdf5(path, big_file)
    elif is_simple_file:
        print(f"[file_opener] Detected simple HDF5 file: {path}")
        return _open_simple_hdf5(path, big_file)
    else:
        raise ValueError(
            f"Unsupported HDF5 file format: {path}\n"
            f"Expected either an MCS file (with 'McsHdf5ProtocolType' attribute) "
            f"or a simple file (with 'recording' dataset)."
        )
